src/Vjezba/Vjezba.Web/Models/Mock/Company.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Vjezba.Web.Models.Mock
{
    public class Company
    {
        public int ID { get; set; }

        [Required]
        [StringLength(100, MinimumLength = 5)]
        public string Name { get; set; }

        [Required(ErrorMessage = "Email je obvezno unijeti (nesto@nesto.com)")]
        public string Email { get; set; }

        public string Address { get; set; }

        [Range(-90, 90)]
        public decimal Latitude { get; set; }

        [Range(-180, 180)]
        public decimal Longitude { get; set; }

        public DateTime DateFrom { get; set; }

        public int CityID { get; set; }

        public City City { get; set; }
    }

}

src/Vjezba/Vjezba.Web/Areas/Admin/Controllers/CityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vjezba.Web.Models.Mock;

namespace Vjezba.Web.Areas.Admin.Controllers
{
    [RouteArea("Admin", AreaPrefix = "Administracija")]
    [RoutePrefix("Gradovi")]
    public class CityController : Controller
    {
        [Route("")]
        public ActionResult Index()
        {
            var cities = MockCityRepository.GetInstance().All()
                .ToList();

            //Naziv view-a se automatski skuzi iz naziva akcije controller-a, dovoljno je proslijediti samo model
            return View(cities);
        }

        [Route("detalji")]
        public ActionResult Details(int? id = null)
        {
            if (id == null)
                return View();

            var model = MockCityRepository.GetInstance().FindByID(id.Value);

            return View(model);
        }

        [Route("detalji/info")]
        public ActionResult DetailsPartial(int? id = null)
        {
            if (id == null)
                return null;

            var model = MockCityRepository.GetInstance().FindByID(id.Value);

            if (model == null)
                return null;

            return PartialView("_DetailsPartial", model);
        }

    }

}

src/Vjezba/Vjezba.Web/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vjezba.Web.Models;
using Vjezba.Web.Models.Mock;

namespace Vjezba.Web.Controllers
{
    [RoutePrefix("komp")]
    public class CompanyController : Controller
    {
        public ActionResult Index(string query)
        {
            var companiesQuery = MockCompanyRepository.GetInstance().All();

            if (!string.IsNullOrWhiteSpace(query))
                companiesQuery = companiesQuery.Where(p => p.Name.Contains(query));

            var model = companiesQuery.OrderBy(p => p.ID).ToList();
            return View(model);
        }

        [HttpPost]
        public ActionResult IndexAjax(CompanyFilterModel model)
        {
            var companiesQuery = MockCompanyRepository.GetInstance().All();

            if (!string.IsNullOrWhiteSpace(model.Name))
                companiesQuery = companiesQuery.Where(p => p.Name.Contains(model.Name));

            if (!string.IsNullOrWhiteSpace(model.Address))
                companiesQuery = companiesQuery.Where(p => p.Address.Contains(model.Address));

            if (!string.IsNullOrWhiteSpace(model.Email))
                companiesQuery = companiesQuery.Where(p => p.Email.Contains(model.Email));

            if (!string.IsNullOrWhiteSpace(model.CityName))
                companiesQuery = companiesQuery.Where(p => p.City.Name.Contains(model.CityName));

            var data = companiesQuery.OrderBy(p => p.ID).ToList();

            //Iskoristit ćemo postojeći view Index. Potrebno je eksplicitno reći koji view želimo renderirati
            //jer se inače pokušava pronaći template AdvancedSearch.cshtml
            return PartialView("_IndexTable", data);
        }

        public List<SelectListItem> listCities()
        {
            var cityList = MockCityRepository.GetInstance().All().ToList();
            var cityNameList = new List<SelectListItem>();

            var listItem = new SelectListItem();
            listItem.Text = "Select";
            listItem.Value = "";
            cityNameList.Add(listItem);

            foreach (City city in cityList)
            {
                listItem = new SelectListItem();
                listItem.Text = city.Name;
                listItem.Value = city.ID.ToString();
                cityNameList.Add(listItem);
            }

            return cityNameList;
        }

        public ActionResult Create()
        {
            ViewBag.ListaGradova = listCities();

            return View();
        }

        [HttpPost]
        public ActionResult Create(Company model)
        {
            if (ModelState.IsValid)
            {
                model.ID = MockCompanyRepository.GetInstance().All()
                    .Max(p => p.ID) + 1;

                MockCompanyRepository.GetInstance().InsertOrUpdate(model);

                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.ListaGradova = listCities();

                return View(model);
            }
        }

        public ActionResult Edit(int id)
        {
            var model = MockCompanyRepository.GetInstance().FindByID(id);
            ViewBag.ListaGradova = listCities();

            return View(model);
        }

        [HttpPost]
        [ActionName("Edit")]
        public ActionResult EditPost(int id)
        {
            var model = MockCompanyRepository.GetInstance().FindByID(id);
            var didUpdateModelSucceed = this.TryUpdateModel(model);

            if (didUpdateModelSucceed && ModelState.IsValid)
            {
                MockCompanyRepository.GetInstance().InsertOrUpdate(model);
                return RedirectToAction("Index");
            }

            ViewBag.ListaGradova = listCities();
            return View(model);
        }


        public ActionResult Details(int? id = null)
        {
            if (id == null)
                return View();

            var model = MockCompanyRepository.GetInstance().FindByID(id.Value);

            return View(model);
        }

        [Route("pretraga/{q:alpha:length(2,5)}")]
        public ActionResult Search(string q)
        {
            //Kada se bude radilo s bazom podataka, ova metoda još neće "otići" u bazu po podatke
            var query = MockCompanyRepository.GetInstance().All();

            if (!string.IsNullOrWhiteSpace(q))
                query = query.Where(p => p.Name.Contains(q));

            //Kada se bude radilo s bazom podataka, tek ova metoda bi generirala ispravni SQL i izvršila upit na bazi
            //te vratila samo potrebne rezultate
            var model = query.ToList();

            return View("Index", model);
        }


    }
}

src/Vjezba/Vjezba.Web/Views/Company/Create.cshtml
﻿@model Vjezba.Web.Models.Mock.Company
@{
    ViewBag.Title = "Create new company";
}
<ol class="breadcrumb">
    <li>@Html.ActionLink("Home", "Index", "Home")</li>
    <li>@Html.ActionLink("Pregled kompanija", "Index")</li>
    <li class="active">Kreiranje nove kompanije</li>
</ol>
<h2>Create new company</h2>
@using (Html.BeginForm())
{
    <text>
        @Html.Partial("_CreateOrEdit")
    </text>

}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

src/Vjezba/Vjezba.Web/Views/Company/Details.cshtml
﻿﻿﻿@model Vjezba.Web.Models.Mock.Company
@{
    ViewBag.Title = "Detalji kompanije";
}
<ol class="breadcrumb">
    <li>@Html.ActionLink("Home", "Index", "Home")</li>
    <li>@Html.ActionLink("Pregled kompanija", "Index")</li>
    <li class="active">Detalji o kompaniji</li>
</ol>
<h2>Pregled detalja kompanije</h2>
@if (Model == null)
{
    <div class="alert alert-danger" role="alert">Ne postoji odabrana kompanija!</div>
}
else
{
    <table class="table table-condensed">
        <tbody>
            <tr>
                <th>ID</th>
                <td>@Model.ID</td>
            </tr>
            <tr>
                <th>Naziv</th>
                <td>@Model.Name</td>
            </tr>
            <tr>
                <th>Adresa</th>
                <td>@Model.Address</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>@Model.Email</td>
            </tr>
            <tr>
                <th>Grad</th>
                <td><a href="#" class="city-popover">@Model.City.Name</a></td>
            </tr>
            <tr>
                <td colspan="2">@Html.ActionLink("Uredi", "Edit", new { id = Model.ID })</td>
            </tr>
        </tbody>
    </table>
}
<div class="hidden" id="popover-data">
    @Html.Action("DetailsPartial", "City", new { id = Model.CityID, area = "Admin" })
</div>
@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $(".city-popover").popover({ content: $("#popover-data").html(), html: true });
        });
    </script>

}

src/Vjezba/Vjezba.Web/Views/Company/Edit.cshtml
﻿﻿﻿@model Vjezba.Web.Models.Mock.Company

@{
    ViewBag.Title = "Create new company";
}

<ol class="breadcrumb">
    <li>@Html.ActionLink("Home", "Index", "Home")</li>
    <li>@Html.ActionLink("Pregled kompanija", "Index")</li>
    <li class="active">Uređivanje kompanije @Model.Name</li>
</ol>

<h2>Edit company data</h2>

@using (Html.BeginForm())
{

    <text>
        @Html.Partial("_CreateOrEdit")
        @Html.HiddenFor(p => p.ID)
    </text>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

src/Vjezba/Vjezba.Web/Views/Company/Index.cshtml
@model List<Vjezba.Web.Models.Mock.Company>
@{
    ViewBag.Title = "Pregled kompanija";
}

<div class="panel panel-heading">
    <div class="row">
        <div class="col-xs-8">
            <h2>Pregled kompanija</h2>
        </div>
        <div class="col-xs-4 text-right">
            <a href="@Url.Action("Create")" style="margin-top: 20px;" class="btn btn-success">Dodaj novu kompaniju</a>
        </div>
    </div>
</div>

@Html.Partial("_CompanyFilter", new Vjezba.Web.Models.CompanyFilterModel())
@Html.Partial("_IndexTable", Model)


@section scripts {

<style>

    tr {
        opacity: 0.6;
    }

    tr:hover {
        opacity: 1;
    }

    .bold {
        font-weight: bold;
    }

</style>

<script type="text/javascript">

    $(function () {
        $("#headerRow").css('opacity', '1');
    });

    function onClickBold(tr) {
        $(tr).toggleClass('bold');
    }

    $(function () {
        $('button').click(function () {
            var str = $("form").serialize();
            $.ajax({
                type: "POST",
                data: str,
                url: "@Url.Action("IndexAjax", "Company")",
            }).done(function (res) {
                $("#companiesTable").replaceWith(res);
            })
        });
    });

</script>

}

src/Vjezba/Vjezba.Web/Views/Company/_CompanyFilter.cshtml
﻿﻿@model Vjezba.Web.Models.CompanyFilterModel
<div class="row">
    <div class="col-md-12">
        <form action="@Url.Action("Index")" method="post" class="form-inline">
            <div class="form-group">
                @Html.EditorFor(p => p.Name, new { htmlAttributes = new { @class = "form-control", placeholder = "Pretraga po nazivu" } })
            </div>
            <div class="form-group">
                @Html.TextBoxFor(p => p.Address, new { @class = "form-control", placeholder = "Pretraga po adresi" })
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="@Html.NameFor(p => p.Email)" placeholder="Pretraga po e-mailu">
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="@Html.NameFor(p => p.CityName)" placeholder="Pretraga po gradu">
            </div>
            <button type="button" class="btn btn-default">Pretraga</button>
        </form>
    </div>
</div>

src/Vjezba/Vjezba.Web/Views/Company/_CreateOrEdit.cshtml
﻿@model Vjezba.Web.Models.Mock.Company
<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.CityID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.CityID, (IEnumerable<SelectListItem>)ViewBag.ListaGradova, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.City.ID, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Latitude, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Latitude, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Latitude, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Longitude, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Longitude, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Longitude, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.DateFrom, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DateFrom, new { htmlAttributes = new { @class = "form-control input-group date-picker" } })
            @Html.ValidationMessageFor(model => model.DateFrom, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>

src/Vjezba/Vjezba.Web/Views/Company/_IndexTable.cshtml
@model List<Vjezba.Web.Models.Mock.Company>



@{
    ViewBag.Title = "_IndexTable";
}

<table id="companiesTable" class="table table-condensed table-hover" style="margin-top:10px">
    <thead>
        <tr id="headerRow">
            <th>#</th>
            <th>Naziv</th>
            <th>Adresa</th>
            <th>Datum osnivanja</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var company in Model)
        {
            <tr onclick="onClickBold(this)">
                <td>@company.ID</td>
                <td>@Html.ActionLink(company.Name, "Details", new { id = company.ID })</td>
                <td>@company.Address</td>
                <td>@company.DateFrom.ToShortDateString()</td>
                <td>@Html.ActionLink("Uredi", "Edit", new { id = company.ID })</td>
            </tr>
        }
    </tbody>
</table>